/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author HP
 */
public class MainPage extends javax.swing.JFrame {

    PanelPerjalanan panelPerjalanan;
    PanelPesan panelPesan;
    PanelTiket panelTiket;
    PanelData panelData;

    CardLayout layout;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        layout = (CardLayout) mainPanel.getLayout();

        panelPerjalanan = new PanelPerjalanan();
        panelPesan = new PanelPesan();
        panelTiket = new PanelTiket();
        panelData = new PanelData();

        mainPanel.add("perjalanan", panelPerjalanan);
        mainPanel.add("pesan", panelPesan);
        mainPanel.add("tiket", panelTiket);
        mainPanel.add("data", panelData);

        layout.show(mainPanel, "perjalanan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPerjalanan = new javax.swing.JButton();
        btnTiket = new javax.swing.JButton();
        btnPesan = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));

        btnPerjalanan.setText("Perjalanan");
        btnPerjalanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerjalananActionPerformed(evt);
            }
        });

        btnTiket.setText("Tiket");
        btnTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiketActionPerformed(evt);
            }
        });

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        mainPanel.setMinimumSize(new java.awt.Dimension(600, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        jButton1.setText("Data Pesanan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPerjalanan)
                    .addComponent(btnTiket)
                    .addComponent(btnPesan)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPerjalanan)
                .addGap(18, 18, 18)
                .addComponent(btnTiket)
                .addGap(18, 18, 18)
                .addComponent(btnPesan)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(465, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerjalananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerjalananActionPerformed
        panelPerjalanan.refresh();
        layout.show(mainPanel, "perjalanan");
    }//GEN-LAST:event_btnPerjalananActionPerformed

    private void btnTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiketActionPerformed
        panelTiket.refresh();
        layout.show(mainPanel, "tiket");
    }//GEN-LAST:event_btnTiketActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        panelPesan.refresh();
        panelPesan.clearnoti();
        layout.show(mainPanel, "pesan");
    }//GEN-LAST:event_btnPesanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelData.refresh();
        layout.show(mainPanel, "data");    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerjalanan;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnTiket;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
