/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import entities.Perjalanan;
import entities.Tiket;
import helpers.TabelPerjalanan;
import helpers.TabelTiket;
import java.util.List;
import models.PerjalananDAO;
import models.PerjalananSql;
import models.TiketDAO;
import models.TiketSql;

/**
 *
 * @author HP
 */
public class PanelTiket extends javax.swing.JPanel {

    TiketDAO dao;
    PerjalananDAO daoPerjalanan;
    List<Tiket> dataTiket;
    List<Perjalanan> dataPerjalanan;
    int harga = 0;
    boolean editMode = false;

    /**
     * Creates new form PanelTiket
     */
    public PanelTiket() {

        initComponents();
        dao = new TiketSql();
        daoPerjalanan = new PerjalananSql();
        refresh();
    }

    private void clear() {
        txtIdPerjalanan.setText("");
        txtIdTiket.setText("");
        txtJumlah.setText("");
        btnHapus.setEnabled(false);
    }

    public void refresh() {
        dataPerjalanan = daoPerjalanan.selectAll();
        tblPerjalanan.setModel(new TabelPerjalanan(dataPerjalanan));
        dataTiket = dao.selectAll();
        tblTiket.setModel(new TabelTiket(dataTiket));
        txtIdTiket.setEnabled(true);
        clear();
    }

    private Perjalanan getPerjalananById(String id) {
        for (Perjalanan perjalanan : dataPerjalanan) {
            if (perjalanan.idperjalanan.equals(id)) {
                return perjalanan;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdTiket = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdPerjalanan = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerjalanan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTiket = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("ID Tiket");

        btnSimpan.setBackground(new java.awt.Color(51, 153, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Perjalanan");

        jLabel3.setText("Jumlah Tiket");

        txtIdPerjalanan.setEnabled(false);

        tblPerjalanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPerjalanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPerjalananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPerjalanan);

        tblTiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTiketMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTiket);

        btnHapus.setBackground(new java.awt.Color(153, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel4.setText("Pilih Perjalanan");

        jLabel5.setText("Tiket Tersedia ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan))
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtIdPerjalanan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSimpan)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdPerjalanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        txtIdTiket.setEnabled(true);
        String idperjalanan = txtIdPerjalanan.getText();
        String idtiket = txtIdTiket.getText();
        int jumlah = Integer.parseInt(txtJumlah.getText());
        Perjalanan perjalanan = getPerjalananById(idperjalanan);
        int harga = perjalanan.toharga();
        Tiket newtiket = new Tiket(idtiket, jumlah,harga);
        newtiket.harga=harga;
        newtiket.idperjalanan = perjalanan;

        if (editMode == false) {
            dao.insert(newtiket);
        } else {
            dao.update(newtiket);
        }

        refresh();
        clear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblPerjalananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPerjalananMouseClicked
        if (evt.getClickCount() == 2) {
            txtIdTiket.setEnabled(true);

            Perjalanan perjalanan = dataPerjalanan.get(tblPerjalanan.getSelectedRow());

            txtIdPerjalanan.setText(perjalanan.idperjalanan);
            txtIdPerjalanan.setEnabled(false);

        }
    }//GEN-LAST:event_tblPerjalananMouseClicked

    private void tblTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTiketMouseClicked
        if (evt.getClickCount() == 2) {
            editMode = true;
            btnHapus.setEnabled(true);

            Tiket tiket = dataTiket.get(tblTiket.getSelectedRow());

            txtIdPerjalanan.setText(tiket.idperjalanan.idperjalanan);
            txtIdTiket.setText(tiket.idtiket);
            txtJumlah.setText(String.valueOf(tiket.jumlah));

            txtIdPerjalanan.setEnabled(false);
            txtIdTiket.setEnabled(false);

        }
    }//GEN-LAST:event_tblTiketMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        txtIdTiket.setEnabled(true);

        dao.delete(txtIdTiket.getText());
        refresh();
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblPerjalanan;
    private javax.swing.JTable tblTiket;
    private javax.swing.JTextField txtIdPerjalanan;
    private javax.swing.JTextField txtIdTiket;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
